//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SenorQuinuapata.GestionCostos.DataAccess.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class Activo_biologico
    {
        public int id { get; set; }
        public string codigo { get; set; }
        public Nullable<System.DateTime> fecha_ingreso { get; set; }
        public Nullable<System.DateTime> fecha_salida { get; set; }
        public string ubicacion { get; set; }
        public string genero { get; set; }
        public Nullable<int> numero_parto { get; set; }
        public Nullable<System.DateTime> fecha_inicio_empadre { get; set; }
        public Nullable<System.DateTime> fecha_fin_empadre { get; set; }
        public string raza { get; set; }
        public Nullable<decimal> valor_inicial { get; set; }
        public Nullable<decimal> tasa_depreciacion { get; set; }
        public Nullable<decimal> depreciacion_acumulada { get; set; }
        public Nullable<decimal> depreciacion_diaria { get; set; }
        public string estado { get; set; }
        public Nullable<decimal> valor_neto { get; set; }
        public string observacion { get; set; }
    }
}
