//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SenorQuinuapata.GestionCostos.DataAccess.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class Consumo
    {
        public int id { get; set; }
        public Nullable<int> cantidad { get; set; }
        public Nullable<System.DateTime> fecha { get; set; }
        public Nullable<int> id_producto { get; set; }
        public Nullable<int> id_departamento { get; set; }
        public Nullable<decimal> md { get; set; }
        public Nullable<decimal> mi { get; set; }
        public string tipo { get; set; }
        public Nullable<decimal> total { get; set; }
    
        public virtual Departamento Departamento { get; set; }
        public virtual Producto Producto { get; set; }
    }
}
