//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SenorQuinuapata.GestionCostos.DataAccess.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class Flujo_unidades_departamento
    {
        public int id { get; set; }
        public Nullable<int> id_departamento { get; set; }
        public Nullable<System.DateTime> fecha { get; set; }
        public Nullable<int> unidades_iniciales_proceso { get; set; }
        public Nullable<int> unidades_agregados_nacidos { get; set; }
        public Nullable<int> unidades_transferidas_recria { get; set; }
        public Nullable<int> unidades_finales_proceso { get; set; }
        public Nullable<int> unidades_transferidas_mortalidad { get; set; }
        public Nullable<int> unidades_recibidas_lactancia { get; set; }
        public Nullable<int> unidades_transferidas_ventas { get; set; }
        public Nullable<int> unidades_transferidas_engorde { get; set; }
        public Nullable<int> unidades_recibidas_recria { get; set; }
        public Nullable<int> unidades_transferidas_descarte { get; set; }
        public Nullable<int> unidades_transferidas_activo { get; set; }
        public Nullable<int> unidades_recibidas_engorde { get; set; }
        public Nullable<int> unidades_recibidas_activo { get; set; }
    
        public virtual Departamento Departamento { get; set; }
    }
}
